### ISSUE TITLE
NIRCam SW distortion center position

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#226]
<a href="https://github.com/JarronL"><img src="https://avatars3.githubusercontent.com/u/17557291?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JarronL](https://github.com/JarronL)**
_Friday Jul 20, 2018 at 00:49 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/issues/226_

----

In checking out the distortion results in v0.7.0, I noticed resulting PSFs getting shifted in ways I was not expecting. These shifts depend on values specified in `detector_position` attribute. For the SW modules, I would have expected any PSF shifting to be relative to the center of the entire focal plane rather than the center of a given detector. 

For instance, setting `detector='A1'` and `detector_position=(1024,1024)` shows a well-centered PSF, whereas values of (0,0), (0,2047), (2047,0), and (2047,2047) all show PSFs shifted diagonally by about 0.47". However, SWA and SWB consist of four detectors with the center of the field situated at their four adjoining corners. I would have expected that center of the field to be the preferential position where the PSF is "unshifted." This appears to be a consequence of the fact that the `apply_distortion` function uses the detector-specific aperture (e.g., `NRCA1_FULL`), so it's always using the center of the detector as the relative position to determine PSF shifting.

**Comment by mperrin** [comment]
@shanosborne are you comfortable that this issue has been addressed by your PR #229? If you agree let me know and we can close this issue.

**Comment by shanosborne** [comment]
@mperrin Yes - I am comfortable that #229 will fix this issue (once the PR has been finalized- I still have that 1 mean vs median question)

**Comment by mperrin** [comment]
Fixed by #229
